# Generated by Django 2.1.7 on 2019-04-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='detail',
            field=models.CharField(default='', max_length=400),
        ),
    ]
