# Generated by Django 2.1.7 on 2019-04-12 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190412_0447'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='object',
            new_name='object1',
        ),
    ]
